// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using BecomeCaleb_WEB.Models.CalebTbl;

namespace BecomeCaleb_WEB.Models.CalebTbl
{
    public partial class CalebContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
