// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.TwoMitesTbl;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BecomeCaleb_WEB.Models.TwoMitesTbl
{
    public partial interface ITwoMitesContextProcedures
    {
    }
}
