// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using BecomeCaleb_WEB.Models.TwoMitesTbl;

namespace BecomeCaleb_WEB.Models.TwoMitesTbl
{
    public partial class TwoMitesContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
