// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.TwoMitesTbl;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BecomeCaleb_WEB.Models.TwoMitesTbl
{
    public partial class TwoMitesContext
    {
        private ITwoMitesContextProcedures _procedures;

        public virtual ITwoMitesContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TwoMitesContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITwoMitesContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class TwoMitesContextProcedures : ITwoMitesContextProcedures
    {
        private readonly TwoMitesContext _context;

        public TwoMitesContextProcedures(TwoMitesContext context)
        {
            _context = context;
        }
    }
}
