// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.CalebTbl;
using BecomeCaleb_WEB.Models.CalebTbl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BecomeCaleb_WEB.Models.CalebTbl.Configurations
{
    public partial class _TCDiaryConfiguration : IEntityTypeConfiguration<_TCDiary>
    {
        public void Configure(EntityTypeBuilder<_TCDiary> entity)
        {
            entity.HasKey(e => e.DiarySeq)
                .HasName("PK___TCDiary__DC076EFD3A2E4167");

            entity.HasAnnotation("Relational:Comment", "일기");

            entity.Property(e => e.DiarySeq).HasComment("일기내부코드");

            entity.Property(e => e.ChurchSeq).HasComment("교회내부코드");

            entity.Property(e => e.InDate).HasComment("일자");

            entity.Property(e => e.LastDateTime).HasComment("최종작업일시");

            entity.Property(e => e.LastUserSeq).HasComment("최종작업자");

            entity.Property(e => e.Record).HasComment("일기본문");

            entity.Property(e => e.Remark).HasComment("비고");

            entity.Property(e => e.Title).HasComment("일기제목");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TCDiary> entity);
    }
}
