// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.CalebTbl;
using BecomeCaleb_WEB.Models.CalebTbl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BecomeCaleb_WEB.Models.CalebTbl.Configurations
{
    public partial class _TCMissionConfiguration : IEntityTypeConfiguration<_TCMission>
    {
        public void Configure(EntityTypeBuilder<_TCMission> entity)
        {
            entity.HasKey(e => e.MissionSeq)
                .HasName("PK___TCMissi__892269AD4B2DBD1A");

            entity.HasAnnotation("Relational:Comment", "미션");

            entity.Property(e => e.MissionSeq).HasComment("미션내부코드");

            entity.Property(e => e.CategoryMMCode).HasComment("미션Major-Minor코드");

            entity.Property(e => e.ChurchSeq).HasComment("교회내부코드");

            entity.Property(e => e.DiarySeq).HasComment("일기내부코드");

            entity.Property(e => e.LastDateTime).HasComment("최종작업일시");

            entity.Property(e => e.LastUserSeq).HasComment("최종작업자");

            entity.Property(e => e.Remark).HasComment("비고");

            entity.Property(e => e.Result).HasComment("미션결과");

            entity.Property(e => e.Title).HasComment("미션제목");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TCMission> entity);
    }
}
