// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.TwoMitesTbl;
using BecomeCaleb_WEB.Models.TwoMitesTbl.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BecomeCaleb_WEB.Models.TwoMitesTbl.Configurations
{
    public partial class _TFAMinorConfiguration : IEntityTypeConfiguration<_TFAMinor>
    {
        public void Configure(EntityTypeBuilder<_TFAMinor> entity)
        {
            entity.HasIndex(e => new { e.MajorSeq, e.MinorSeq }, "_TFAMinor_NIndex")
                .IsClustered();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TFAMinor> entity);
    }
}
