// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.TwoMitesTbl;
using BecomeCaleb_WEB.Models.TwoMitesTbl.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BecomeCaleb_WEB.Models.TwoMitesTbl.Configurations
{
    public partial class _TFAMajorConfiguration : IEntityTypeConfiguration<_TFAMajor>
    {
        public void Configure(EntityTypeBuilder<_TFAMajor> entity)
        {
            entity.HasKey(e => e.MajorSeq)
                .HasName("PK___TFAMajo__7A66DBAAA68CA268");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TFAMajor> entity);
    }
}
