// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.TwoMitesTbl;
using BecomeCaleb_WEB.Models.TwoMitesTbl.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BecomeCaleb_WEB.Models.TwoMitesTbl.Configurations
{
    public partial class _TFBibleConfiguration : IEntityTypeConfiguration<_TFBible>
    {
        public void Configure(EntityTypeBuilder<_TFBible> entity)
        {
            entity.HasKey(e => e.BibleSeq)
                .HasName("PK___TFBible__45FD773B11A55B92");

            entity.Property(e => e.BibleSeq).HasComment("성경내부코드");

            entity.Property(e => e.Chapter).HasComment("장");

            entity.Property(e => e.Descript).HasComment("말씀");

            entity.Property(e => e.Testament).HasComment("성경약어");

            entity.Property(e => e.Verse).HasComment("절");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TFBible> entity);
    }
}
