// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BecomeCaleb_WEB.Models.TwoMitesTbl;
using BecomeCaleb_WEB.Models.TwoMitesTbl.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BecomeCaleb_WEB.Models.TwoMitesTbl.Configurations
{
    public partial class _TFUserConfiguration : IEntityTypeConfiguration<_TFUser>
    {
        public void Configure(EntityTypeBuilder<_TFUser> entity)
        {
            entity.HasKey(e => new { e.ChurchSeq, e.UserSeq })
                .HasName("TPK_TMEmp");

            entity.HasAnnotation("Relational:Comment", "사용자마스터");

            entity.Property(e => e.ChurchSeq).HasComment("교회내부코드");

            entity.Property(e => e.UserSeq)
                .ValueGeneratedOnAdd()
                .HasComment("사용자코드");

            entity.Property(e => e.Empid).HasComment("사용자번호");

            entity.Property(e => e.IsAdministrator)
                .IsFixedLength()
                .HasComment("관리자여부(1 == 관리자, 0 == 일반)");

            entity.Property(e => e.IsSaved)
                .IsFixedLength()
                .HasComment("구원여부(1 == 성도, 0 == 일반)");

            entity.Property(e => e.LastDateTime).HasComment("최종작업일시");

            entity.Property(e => e.LastUserSeq).HasComment("최종작업자");

            entity.Property(e => e.ResidID).HasComment("계정");

            entity.Property(e => e.UserName).HasComment("사용자명");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TFUser> entity);
    }
}
